### ISSUE TITLE
encountering an error

### ISSUE THREAD

**Issue by vibhavk** [pnkjwrk3/facerecognition_lbph#2]
Traceback (most recent call last):
  File "train_model.py", line 16, in <module>
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'

**Comment by pnkjwrk3** [comment]
You have a missing dependency.
Try installing opencv-contrib using the following command: 

> pip install opencv-contrib-python
